import { useMemo } from 'react';
import { useCurrency } from '../../context/CurrencyContext';
import { useI18n } from '../../context/I18nContext';
import { useTransactions as useTransactionsQuery } from '../../hooks/api/useTransactions';
import type { Transaction as ApiTransaction } from '../../hooks/api/useTransactions';
import { formatCurrency, formatDate, parseDateFromAPI } from '../../utils/format';
import { confirmCopy, dueToConfirm } from '../../utils/confirmReceipt';
import { referenceChip } from '../../utils/referenceMonth';
import type { Transaction } from '../../types';
import { TransactionType } from '../../lib/enums';

interface DueToConfirmPanelProps {
  householdId?: string;
  /** Opens the confirmation dialog for a row. */
  onConfirm: (transaction: Transaction) => void;
  /** Only the occurrences generated by a recurrence (the recurring page). */
  onlyRecurring?: boolean;
  readOnly?: boolean;
}

const toRow = (t: ApiTransaction): Transaction | null => {
  if (t.type !== 'INCOME' && t.type !== 'EXPENSE') return null;
  const date = parseDateFromAPI(t.date);
  if (Number.isNaN(date.getTime())) return null;
  return {
    id: t.id,
    description: t.description,
    amount: Number(t.amount),
    type: t.type === 'INCOME' ? TransactionType.INCOME : TransactionType.EXPENSE,
    categoryName: t.categoryName as string | undefined,
    date,
    paid: t.paid,
    accountId: t.accountId,
    recurringTransactionId: t.recurringTransactionId,
    notes: (t as { notes?: string }).notes,
    competenceMonth: t.competenceMonth ?? null,
  };
};

/**
 * "A confirmar": pending income and expenses whose expected day has come (today or earlier), oldest first. Each row opens
 * the "Confirmar recebimento / pagamento" dialog, so a forecast (a meal voucher that should have been deposited) is
 * confirmed with the amount and the date it really had.
 */
export const DueToConfirmPanel = ({ householdId, onConfirm, onlyRecurring = false, readOnly = false }: DueToConfirmPanelProps) => {
  const { baseCurrency } = useCurrency();
  const { t } = useI18n();
  const today = useMemo(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), now.getDate());
  }, []);
  const { data } = useTransactionsQuery({ householdId, paid: false, endDate: today, limit: 50 });

  const rows = useMemo(() => {
    const converted = (data?.data ?? []).map(toRow).filter((r): r is Transaction => r !== null && (!onlyRecurring || !!r.recurringTransactionId));
    return dueToConfirm(converted, today);
  }, [data, today, onlyRecurring]);

  if (rows.length === 0) return null;

  return (
    <section
      data-testid="due-to-confirm"
      aria-label={t.toConfirmTitle || 'A confirmar'}
      className="mb-6 rounded-md border border-yellow-200 dark:border-yellow-900/60 bg-yellow-50/60 dark:bg-yellow-900/10"
    >
      <div className="px-4 sm:px-6 py-3 border-b border-yellow-200/70 dark:border-yellow-900/40">
        <h2 className="text-sm font-light tracking-tight text-gray-900 dark:text-white">
          {t.toConfirmTitle || 'A confirmar'} <span className="text-gray-500 dark:text-gray-400">({rows.length})</span>
        </h2>
        <p className="text-xs font-light text-gray-500 dark:text-gray-400">
          {t.toConfirmHint || 'Previstos que já deveriam ter acontecido. Confirme o valor e a data reais.'}
        </p>
      </div>
      <ul className="divide-y divide-yellow-200/70 dark:divide-yellow-900/40">
        {rows.map((row) => {
          const chip = referenceChip(row);
          const copy = confirmCopy(row.type);
          return (
            <li key={row.id} className="px-4 sm:px-6 py-3 flex flex-wrap items-center justify-between gap-3">
              <div className="min-w-0">
                <p className="text-sm font-light text-gray-900 dark:text-white truncate">{row.description || '-'}</p>
                <p className="text-xs font-light text-gray-500 dark:text-gray-400">
                  {formatDate(row.date)}
                  {chip ? <span data-testid="reference-chip" className="ml-2 text-blue-600 dark:text-blue-400">{chip}</span> : null}
                </p>
              </div>
              <div className="flex items-center gap-3">
                <span className={`text-sm font-light ${row.type === TransactionType.INCOME ? 'text-green-500' : 'text-red-500'}`}>
                  {row.type === TransactionType.INCOME ? '+' : '-'}{formatCurrency(Math.abs(row.amount), baseCurrency)}
                </span>
                {!readOnly && (
                  <button
                    type="button"
                    onClick={() => onConfirm(row)}
                    className="px-3 py-1.5 text-xs font-light text-white bg-primary-600 dark:bg-primary-500 rounded-md hover:opacity-80 transition-opacity"
                  >
                    {row.type === TransactionType.EXPENSE ? (t.confirmPaymentAction || copy.action) : (t.confirmReceiptAction || copy.action)}
                  </button>
                )}
              </div>
            </li>
          );
        })}
      </ul>
    </section>
  );
};
